language: node_js
sudo: false
node_js: 8.8.0
install: npm install
jobs:
  include:
    - stage: Build 
      script: npm run build
    - stage: Functional Test
      script: npm start & (wait-on http://localhost:3000 && cypress run)
