language: node_js
sudo: false
node_js: 8.8.0
cache:
  directories:
    - node_modules
    - dist
install: npm install
stages:
  - build
  - functional-test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: build 
      script: npm run build
    - stage: functional-test
      script: npm start & (wait-on http://localhost:3000 && cypress run)
    - stage: deploy 
      script: ./ci/deploy
      deploy: &heroku
        provider: heroku
        app: seba-caro
        api_key:
          secure: "$HEROKU_KEY"